LeokaEstetica.Platform.Controllers/Profile/ProfileController.cs
LeokaEstetica.Platform.Core/Mapper/MappingProfile.cs
LeokaEstetica.Platform.Database/Abstractions/Profile/IProfileRepository.cs
LeokaEstetica.Platform.Database/Repositories/Profile/ProfileRepository.cs
LeokaEstetica.Platform.Models/Dto/Output/Profile/SkillOutput.cs
LeokaEstetica.Platform.Models/Mappings/Profile/SkillConfiguration.cs
LeokaEstetica.Platform.Services/Abstractions/Profile/IProfileService.cs
LeokaEstetica.Platform.Services/Services/Profile/ProfileService.cs
LeokaEstetica.Platform.Tests/ProfileTests/ProfileSkillsTest.cs

[#31f21xa] Добавление логики вывода списка навыков в профиль пользователя для выбора им.

---

LeokaEstetica.Platform.Services/Services/Project/ProjectService.cs

[fix/10144981-fix-date-in-project-team]Дата команды проекта возвращается без времени.

---

LeokaEstetica.Platform.CallCenter/Abstractions/Project/IProjectModerationService.cs
LeokaEstetica.Platform.CallCenter/LeokaEstetica.Platform.CallCenter.csproj
LeokaEstetica.Platform.CallCenter/Models/Dto/Output/Moderation/ProjectRemarkOutput.cs
LeokaEstetica.Platform.CallCenter/Models/Dto/Output/Moderation/ProjectRemarkResult.cs
LeokaEstetica.Platform.CallCenter/Services/Project/ProjectModerationService.cs
LeokaEstetica.Platform.Controllers/CallCenter/ModerationController.cs
LeokaEstetica.Platform.Core/Data/PgContext.cs
LeokaEstetica.Platform.Core/Enums/RemarkStatusEnum.cs
LeokaEstetica.Platform.Core/Mapper/MappingProfile.cs
LeokaEstetica.Platform.Database/Abstractions/Moderation/Project/IProjectModerationRepository.cs
LeokaEstetica.Platform.Database/Repositories/Moderation/Project/ProjectModerationRepository.cs
LeokaEstetica.Platform.Models/Dto/Input/Moderation/CreateProjectRemarkInput.cs
LeokaEstetica.Platform.Models/Dto/Input/Moderation/ProjectRemarkInput.cs
LeokaEstetica.Platform.Models/Dto/Output/Moderation/Project/ProjectRemarkOutput.cs
LeokaEstetica.Platform.Models/Dto/Output/Moderation/Project/ProjectRemarkResult.cs
LeokaEstetica.Platform.Models/Entities/Moderation/ProjectRemarkEntity.cs
LeokaEstetica.Platform.Models/Entities/Moderation/RemarkStatuseEntity.cs
LeokaEstetica.Platform.Models/Entities/Project/UserProjectEntity.cs
LeokaEstetica.Platform.Models/Entities/User/UserEntity.cs
LeokaEstetica.Platform.Models/Mappings/Moderation/ProjectRemarkConfiguration.cs
LeokaEstetica.Platform.Models/Mappings/Moderation/RemarkStatuseConfiguration.cs
LeokaEstetica.Platform.Notifications/Abstractions/IProjectModerationNotificationService.cs
LeokaEstetica.Platform.Notifications/AutofacModules/NotificationsModule.cs
LeokaEstetica.Platform.Notifications/Services/ProjectModerationNotificationService.cs
LeokaEstetica.Platform.Tests/BaseServiceTest.cs
LeokaEstetica.Platform.Tests/ModerationTests/CreateProjectRemarksTest.cs
LeokaEstetica.Platform.Tests/ModerationTests/EmptyProjectRemarkTest.cs
LeokaEstetica.Platform.Tests/ModerationTests/EmptyRemarkStatuseTest.cs

[feature/moderation-project-remark] Добавление возможности отправки замечаний к проекту.

---

LeokaEstetica.Platform.Models/Dto/Output/Project/UserProjectArchiveResultOutput.cs
LeokaEstetica.Platform.Services/Services/Project/ProjectService.cs
LeokaEstetica.Platform.Tests/ProjectsTests/GetUserProjectsArchiveTest.cs

Замержить перед функционалом удаления.

#11080820 Вывел список проектов в архиве.

---

LeokaEstetica.Platform.Controllers/Project/ProjectController.cs
LeokaEstetica.Platform.Database/Abstractions/Project/IProjectRepository.cs
LeokaEstetica.Platform.Database/Repositories/Project/ProjectRepository.cs
LeokaEstetica.Platform.Notifications/Abstractions/IProjectNotificationsService.cs
LeokaEstetica.Platform.Notifications/Services/ProjectNotificationsService.cs
LeokaEstetica.Platform.Services/Abstractions/Project/IProjectService.cs
LeokaEstetica.Platform.Services/Services/Project/ProjectService.cs

Сначала замержить этот PR, потом уже для вакансий.

#11072166 Добавил удаление проекта из архива.

---

LeokaEstetica.Platform.Controllers/Commerce/CommerceController.cs
LeokaEstetica.Platform.Processing/Abstractions/Commerce/ICommerceService.cs
LeokaEstetica.Platform.Processing/Services/Commerce/CommerceService.cs
LeokaEstetica.Platform.Tests/BaseServiceTest.cs

#10454010 Отображать уведомление о предупреждении о незаполненной анкете при попытке купить тариф.

---

LeokaEstetica.Platform.Controllers/User/UserController.cs
LeokaEstetica.Platform.Core/Constants/GlobalConfigKeys.cs
LeokaEstetica.Platform.Models/Dto/Output/User/AuthProviderConfigOutput.cs
LeokaEstetica.Platform.Services/Abstractions/User/IUserService.cs
LeokaEstetica.Platform.Services/Services/User/UserService.cs
LeokaEstetica.Platform.Tests/BaseServiceTest.cs

Его мержить до аутентификации через провайдеров, так как тут основа.

#18431595 Реализовать ендпоинт для получения ссылок для авторизаций через ВК и Google.

---

LeokaEstetica.Platform.Models/Entities/User/UserEntity.cs

Поправил в миграции + минорный рефач.

#17992348 Ошибка на тесте "Can't cast database type text to Guid" при сохранении анкеты.

---

LeokaEstetica.Platform.Services/Services/Project/ProjectService.cs
LeokaEstetica.Platform.Services/Services/Vacancy/VacancyService.cs

Чужие вакансии не отображаются - это не подтверждаю. Но пофиксил баг с форбиденом (некорректно блокировал страницу).

#20258601 В вакансиях пользователя видны чужие вакансии.

---

LeokaEstetica.Platform.Access/Helpers/HashHelper.cs
LeokaEstetica.Platform.Core/Data/PgContext.cs
LeokaEstetica.Platform.Database.Upgrade/LeokaEstetica.Platform.Database.Upgrade.csproj
LeokaEstetica.Platform.Database.Upgrade/Scripts/016.Esta.DDL_Create_Schema_Templates.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/017.Esta.DDL_Create_Table_ProjectManagmentTaskTemplates.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/018.Esta.DDL_Create_Table_ProjectManagmentTaskStatusTemplates.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/019.Esta.DDL_Create_Table_ProjectManagmentUserTaskTemplates.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/020.Esta.DML_Insert_ProjectManagmentTaskTemplates.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/021.Esta.DML_Insert_ProjectManagmentTaskStatusTemplates.sql
LeokaEstetica.Platform.Models/Entities/Template/ProjectManagmentTaskStatusTemplateEntity.cs
LeokaEstetica.Platform.Models/Entities/Template/ProjectManagmentTaskTemplateEntity.cs
LeokaEstetica.Platform.Models/Entities/Template/ProjectManagmentUserTaskTemplateEntity.cs
LeokaEstetica.Platform.Models/Mappings/Template/ProjectManagmentTaskStatusTemplateConfiguration.cs
LeokaEstetica.Platform.Models/Mappings/Template/ProjectManagmentTaskTemplateConfiguration.cs
LeokaEstetica.Platform.Models/Mappings/Template/ProjectManagmentUserTaskTemplateConfiguration.cs
LeokaEstetica.Platform.Tests/TemplateTests/ProjectManagmentTemplateEntitiesTests.cs

Также добавлен шаблон "Старт". Он содержит минимальный набор статусов.

#25623672 Добавление шаблона Kanban - классический.

---

LeokaEstetica.Platform.Base/Abstractions/Services/Pachca/IPachcaService.cs
LeokaEstetica.Platform.Base/Services/Pachca/PachcaService.cs
LeokaEstetica.Platform.Models/Entities/Project/UserProjectEntity.cs
LeokaEstetica.Platform.Models/Entities/ProjectManagment/UserTaskEntity.cs
LeokaEstetica.Platform.Models/Mappings/Project/ArchivedProjectConfiguration.cs
LeokaEstetica.Platform.Models/Mappings/Project/CatalogProjectConfiguration.cs
LeokaEstetica.Platform.Models/Mappings/ProjectManagment/ProjectTaskConfiguration.cs
LeokaEstetica.Platform.Services/Services/Project/ProjectService.cs

…дерацию + фикс ошибок FK задач проекта.

#26721736 Добавить отправку уведомления в пачку когда создан новый проект.

---

LeokaEstetica.Platform.Core/Enums/ProjectUserStoryStatusEnum.cs
LeokaEstetica.Platform.Core/Mapper/MappingProfile.cs
LeokaEstetica.Platform.Database.Upgrade/Init/DatabaseMigrator.cs
LeokaEstetica.Platform.Database.Upgrade/Scripts/113.esta.ddl_alter_epics.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/114.esta.ddl_create_user_story_statuses.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/115.esta.ddl_create_user_story.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/116.esta.dml_insert_user_story_statuses.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/117.esta.ddl_alter_epics.sql
LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IProjectManagmentRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/ProjectManagmentRepository.cs
LeokaEstetica.Platform.Models/Dto/Input/ProjectManagement/CreateProjectManagementTaskInput.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagment/UserStoryOutput.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagment/UserStoryStatusOutput.cs
LeokaEstetica.Platform.Models/Entities/ProjectManagment/EpicEntity.cs
LeokaEstetica.Platform.Models/Entities/ProjectManagment/UserStoryEntity.cs
LeokaEstetica.Platform.Models/Entities/ProjectManagment/UserStoryStatusEntity.cs
LeokaEstetica.Platform.ProjectManagment/Controllers/ProjectManagmentController.cs
LeokaEstetica.Platform.Services/Abstractions/ProjectManagment/IProjectManagmentService.cs
LeokaEstetica.Platform.Services/Factors/CreateProjectTaskFactory.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/ProjectManagmentService.cs
LeokaEstetica.Platform.Tests/ProjectManagmentTests/CreateProjectTaskTest.cs
LeokaEstetica.Platform.Tests/ProjectManagmentTests/CreateProjectUserStoryTest.cs

**Также будет сделано доп.требование:**
Реализовать ендпоинт, который будет выводить названия статусов истории. На фронте если выбран тип задачи - история, то запускать этот ендпоинт, чтобы подтянуть в выпадающий список статусы для выбора.
**В этот PR также войдут задачи, которые связаны с необходимыми изменениями в этом PR:**
- #30475972 Синхронизировать Id задачи в рамках проекта под разные типы задачи (задача, ошибка, эпик, история).
- #30476418 Добавить в таблицу эпиков поле Id задачи в рамках проекта.

#30277667 Реализовать создание истории/требования.

---

LeokaEstetica.Platform.Core/Enums/SearchAgileObjectTypeEnum.cs
LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IProjectManagmentRepository.cs
LeokaEstetica.Platform.Database/Abstractions/Search/ISearchProjectManagementRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/ProjectManagmentRepository.cs
LeokaEstetica.Platform.Database/Repositories/Search/SearchProjectManagementRepository.cs
LeokaEstetica.Platform.Models/Dto/Input/Search/ProjectManagment/BaseSearchAgileObjectInput.cs
LeokaEstetica.Platform.Models/Dto/Input/Search/ProjectManagment/SearchTaskInput.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagment/EpicTaskOutput.cs
LeokaEstetica.Platform.Models/Dto/Output/Search/ProjectManagement/SearchAgileObjectOutput.cs
LeokaEstetica.Platform.ProjectManagment/Controllers/SearchController.cs
LeokaEstetica.Platform.Services/Abstractions/Search/ProjectManagment/ISearchProjectManagementService.cs
LeokaEstetica.Platform.Services/AutofacModules/ServicesModule.cs
LeokaEstetica.Platform.Services/Services/Search/ProjectManagment/SearchProjectManagementService.cs
LeokaEstetica.Platform.Services/Strategies/ProjectManagement/SprintTaskSearch/BaseSearchAgileObjectAlgorithm.cs
LeokaEstetica.Platform.Services/Strategies/ProjectManagement/SprintTaskSearch/BaseSearchAgileObjectStrategy.cs
LeokaEstetica.Platform.Services/Strategies/ProjectManagement/SprintTaskSearch/SearchAgileObjectByProjectTaskIdStrategy.cs
LeokaEstetica.Platform.Services/Strategies/ProjectManagement/SprintTaskSearch/SearchAgileObjectByTaskDescriptionStrategy.cs
LeokaEstetica.Platform.Services/Strategies/ProjectManagement/SprintTaskSearch/SearchAgileObjectByTaskNameStrategy.cs
LeokaEstetica.Platform.Tests/BaseServiceTest.cs
LeokaEstetica.Platform.Tests/SearchTests/SearchIncludeSprintTaskByProjectTaskIdStrategyTest.cs
LeokaEstetica.Platform.Tests/SearchTests/SearchIncludeSprintTaskByTaskDescriptionStrategyTest.cs
LeokaEstetica.Platform.Tests/SearchTests/SearchIncludeSprintTaskByTaskNameStrategyTest.cs

В рамках задачи сделан крупный рефач, чтобы объединить методы и стратегии поиска.

#31513101 Добавить возможность включить задачу в эпик из таблицы задач эпика.

---

LeokaEstetica.Platform.Database.Upgrade/Scripts/131.esta.ddl_alter_epic_tasks.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/132.esta.ddl_alter_epic_tasks.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/133.esta.ddl_create_uniq_sprint_tasks_sprint_id_project_task_id_idx.sql
LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IProjectManagmentRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/ProjectManagmentRepository.cs
LeokaEstetica.Platform.ProjectManagment/Controllers/ProjectManagmentController.cs
LeokaEstetica.Platform.Services/Abstractions/ProjectManagment/IProjectManagmentService.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/ProjectManagmentService.cs

Поправил ошибку фиксации спринта задачи и его отображение в деталях.

#30957029 Отображать в деталях задачи спринт, в который входит задача.

---

LeokaEstetica.Platform.Models/Mappings/Ticket/MainInfoTicketConfiguration.cs
LeokaEstetica.Platform.Models/Mappings/Ticket/TicketMemberConfiguration.cs
LeokaEstetica.Platform.Models/Mappings/Ticket/TicketMessageConfiguration.cs

Поменял в маппинге сущности типа Даты и времени на тип timestamp with time zone.

#31918294 Фикс ошибки создания тикета. 

---

LeokaEstetica.Platform.Database/Repositories/Subscription/SubscriptionRepository.cs

Убрал костыль в коде для подписок.

#32951401 Ошибка на деве "Не удалось получить неактивную подписку пользователя для сброса аккаунта до бесплатного тарифа".

---

LeokaEstetica.Platform.Base/Abstractions/Repositories/Chat/IChatRepository.cs
LeokaEstetica.Platform.Base/Repositories/Chat/ChatRepository.cs
LeokaEstetica.Platform.Controllers/Chat/ChatController.cs
LeokaEstetica.Platform.Database.Upgrade/Scripts/230.esta.ddl_create_DialogMessages.sql
LeokaEstetica.Platform.Messaging/Services/Chat/ChatService.cs
LeokaEstetica.Platform.Models/Mappings/Communication/DialogMemberConfiguration.cs
LeokaEstetica.Platform.Models/Mappings/Communication/DialogMessageConfiguration.cs
LeokaEstetica.Platform.Models/Mappings/Communication/MainInfoDialogConfiguration.cs
LeokaEstetica.Platform.Notifications/Data/ChatHub.cs
LeokaEstetica.Platform.Notifications/LeokaEstetica.Platform.Notifications.csproj
LeokaEstetica.Platform.Tests/BaseServiceTest.cs

Также поправил ряд критичных багов в работе чата.

#33272844 Подтягиваются сообщения диалога, в котором еще не общались.

---

LeokaEstetica.Platform.Base/Abstractions/Repositories/Chat/IChatRepository.cs
LeokaEstetica.Platform.Base/Repositories/Chat/ChatRepository.cs
LeokaEstetica.Platform.Database/Repositories/Project/ProjectRepository.cs

Поправил. Расширил логику удаления проекта, так как добавили таблицы настроек же у проектов.

#20452096 Ошибка удаления проекта.

---

LeokaEstetica.Platform.Database/Repositories/ProjectManagment/ProjectManagmentRepository.cs

Фикс отображения раб.пространств компании.

#34374493 Скорректировать логику получения раб.пространств в общем пространстве.

---

LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IWikiTreeRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/WikiTreeRepository.cs
LeokaEstetica.Platform.Services/Services/Project/ProjectService.cs
LeokaEstetica.Platform.Tests/BaseServiceTest.cs

#34773615 Расширить логику создания проекта (заводить базовое содержимое для ознакомительной страницы проекта).
#34682929 Расширить логику создания проекта (заводить wiki под создаваемый проект, заводить начальную страницу).

#34682929 Расширить логику создания проекта (заводить wiki под создаваемый проект, заводить начальную страницу).

---

LeokaEstetica.Platform.Core/Constants/ValidationConst.cs
LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IWikiTreeRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/WikiTreeRepository.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagement/WikiTreePageItem.cs
LeokaEstetica.Platform.ProjectManagement/Controllers/WikiController.cs
LeokaEstetica.Platform.ProjectManagement/Validators/GetTreeItemFolderValidator.cs
LeokaEstetica.Platform.Services/Abstractions/ProjectManagment/IWikiTreeService.cs
LeokaEstetica.Platform.Services/Services/Project/ProjectService.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/WikiTreeService.cs
LeokaEstetica.Platform.Tests/BaseServiceTest.cs
LeokaEstetica.Platform.Tests/ProjectManagmentTests/GetTreeItemFolderTest.cs

#34773193 Добавить возможность просмотра структуры папки/страницы Wiki.

---

LeokaEstetica.Platform.Core/Constants/ValidationConst.cs
LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IWikiTreeRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/WikiTreeRepository.cs
LeokaEstetica.Platform.Models/Dto/Input/ProjectManagement/UpdateFolderNameInput.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagement/WikiTreePageItem.cs
LeokaEstetica.Platform.ProjectManagement/Controllers/WikiController.cs
LeokaEstetica.Platform.ProjectManagement/Validators/ChangeFolderNameValidator.cs
LeokaEstetica.Platform.ProjectManagement/Validators/GetTreeItemFolderValidator.cs
LeokaEstetica.Platform.Services/Abstractions/ProjectManagment/IWikiTreeService.cs
LeokaEstetica.Platform.Services/Services/Project/ProjectService.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/WikiTreeService.cs
LeokaEstetica.Platform.Tests/BaseServiceTest.cs
LeokaEstetica.Platform.Tests/ProjectManagmentTests/GetTreeItemFolderTest.cs

#34682939 Добавление возможности переименовать папку в дереве wiki.

---

LeokaEstetica.Platform.Core/Constants/ValidationConst.cs
LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IWikiTreeRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/WikiTreeRepository.cs
LeokaEstetica.Platform.Models/Dto/Input/ProjectManagement/UpdateFolderNameInput.cs
LeokaEstetica.Platform.Models/Dto/Input/ProjectManagement/UpdateFolderPageDescriptionInput.cs
LeokaEstetica.Platform.Models/Dto/Input/ProjectManagement/UpdateFolderPageNameDescriptionInput.cs
LeokaEstetica.Platform.Models/Dto/Input/ProjectManagement/UpdateFolderPageNameInput.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagement/WikiTreePageItem.cs
LeokaEstetica.Platform.ProjectManagement/Controllers/WikiController.cs
LeokaEstetica.Platform.ProjectManagement/Validators/ChangeFolderNameValidator.cs
LeokaEstetica.Platform.ProjectManagement/Validators/ChangePageFolderDescriptionValidator.cs
LeokaEstetica.Platform.ProjectManagement/Validators/ChangePageFolderNameValidator.cs
LeokaEstetica.Platform.ProjectManagement/Validators/GetTreeItemFolderValidator.cs
LeokaEstetica.Platform.Services/Abstractions/ProjectManagment/IWikiTreeService.cs
LeokaEstetica.Platform.Services/Services/Project/ProjectService.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/WikiTreeService.cs
LeokaEstetica.Platform.Tests/BaseServiceTest.cs
LeokaEstetica.Platform.Tests/ProjectManagmentTests/GetTreeItemFolderTest.cs

#34682945 Добавление возможности переименовать страницу в дереве wiki.

---

LeokaEstetica.Platform.Database.Upgrade/Scripts/253.esta.ddl_alter_project_management_transition_intermediate_templates.sql
LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IProjectManagmentRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/ProjectManagmentRepository.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/ProjectManagmentService.cs

Подчистил дубли в БД у переходов, фикс косяков в отображении статусов задачи.

#34983376 При смене статуса задачи в доступных статусах отображаются статусы из другого шаблона.

---

LeokaEstetica.Platform.Database.Upgrade/Scripts/251.esta.ddl_create_wiki_tree_folders.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/257.esta.ddl_create_wiki_tree_folder_relations.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/258.esta.ddl_create_wiki_tree_folder_relations_folder_id_parent_id_child_id.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/259.esta.ddl_alter_wiki_tree_folders.sql
LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IWikiTreeRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/WikiTreeRepository.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagement/WikiTreeItem.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/WikiTreeService.cs

#34682948 Добавление возможности создать папку/страницу в дереве wiki.

---

LeokaEstetica.Platform.Core/Enums/TaskDetailTypeEnum.cs
LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IProjectManagmentRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/ProjectManagmentRepository.cs
LeokaEstetica.Platform.ProjectManagement/Controllers/ProjectManagmentController.cs
LeokaEstetica.Platform.ProjectManagement/Validators/TaskDetailValidator.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/ProjectManagmentService.cs

Добавил определение типа задачи, если не передали с фронта.

#35577792 Ошибка просмотра задачи (упало NRE).

---

LeokaEstetica.Platform.Access/Services/User/AccessUserService.cs

#35130643. Добавил проверку на null.

#35130643. Исправил ошибку при отправке комментария к проекту.

---

LeokaEstetica.Platform.Database.Upgrade/Scripts/290.esta.dml_alter_user_projects.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/291.esta.dml_user_projects_add_notnull.sql

Накатил изменения в базу через миграции.

#25320917. Добавил колонку IsPublic в таблицу UserProjects. 

---

LeokaEstetica.Platform.Access/Services/Moderation/AccessModerationService.cs

Возвращаю признак AccessModeration = false.

#31474001. Подправил ответ в случае если нет доступа к модерации. 

---

LeokaEstetica.Platform.Core/Mapper/MappingProfile.cs

Чтобы пофиксить проблемы с отображением вакансий в приглашении.

#35788144. Исправил маппинг выходной модели вакансий проекта.

---

LeokaEstetica.Platform.Database/Repositories/ProjectManagment/ProjectManagementSettingsRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/SprintRepository.cs
LeokaEstetica.Platform.Models/Dto/Output/Notification/ProjectInviteOutput.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagement/Output/ProjectSettingUserOutput.cs

Нужно поправить вывод на фронте

#36547382 Добавлено форматирование отображаемой даты в администрировании проекта - пользователи/приглашения

---

LeokaEstetica.Platform.Database/Repositories/Config/ProjectSettingsConfigRepository.cs

При заведении рабочего пространства.

#36616304. Добавил запись в таблицу settings.project_user_strategy стратегии представления.

---

LeokaEstetica.Platform.Database.Upgrade/Scripts/301.esta.ddl_create_user_subscriptions_user_id_idx.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/302.esta.ddl_alter_user_subscriptions.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/303.esta.ddl_alter_user_subscriptions.sql
LeokaEstetica.Platform.Database/Repositories/Vacancy/VacancyRepository.cs

Фикс не потребовался, но добавил миграции на будущее для таких кейсов.
Здесь проблема в данных.

#36849963 Ошибка определения подписки пользователя при отправке приглашения в проект.

---

LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IProjectManagmentRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/ProjectManagmentRepository.cs
LeokaEstetica.Platform.ProjectManagement/Controllers/ProjectManagmentController.cs
LeokaEstetica.Platform.Services/Abstractions/ProjectManagment/IProjectManagmentService.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/ProjectManagmentService.cs

Чтобы отображались только те теги, который относятся к проекту.

#35974656. Реализовал фильтр тегов проекта.

---

LeokaEstetica.Platform.Database/Abstractions/Project/IProjectRepository.cs
LeokaEstetica.Platform.Database/Repositories/Project/ProjectRepository.cs
LeokaEstetica.Platform.Services/Services/Project/ProjectService.cs

#37452599 Добавить проверку на владельца при попытке удалить владельца проекта.

---

LeokaEstetica.Platform.Core/Enums/ProjectTaskTypeEnum.cs
LeokaEstetica.Platform.Core/Mapper/MappingProfile.cs
LeokaEstetica.Platform.Database.Upgrade/Scripts/309.esta.dml_insert_task_status_templates.sql
LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IProjectManagmentRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/ProjectManagmentRepository.cs
LeokaEstetica.Platform.Models/Dto/Base/ProjectManagement/BaseTaskStatusOutput.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagment/StoryAndEpicSystemStatusOutput.cs
LeokaEstetica.Platform.Models/Dto/Output/Template/ProjectManagmentTaskOutput.cs
LeokaEstetica.Platform.Models/Dto/Output/Template/ProjectManagmentTaskStatusTemplateOutput.cs
LeokaEstetica.Platform.Models/Dto/Output/Template/ProjectManagmentTaskTemplateEntityResult.cs
LeokaEstetica.Platform.Models/Entities/Template/ProjectManagmentTaskStatusTemplateEntity.cs
LeokaEstetica.Platform.Services/Abstractions/ProjectManagment/IDistributionStatusTaskService.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/DistributionStatusTaskService.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/ProjectManagementTemplateService.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/ProjectManagmentService.cs

Скорректировал логику (но остались некорректности при распределении). Также ускорил загрузку раб.пространства ~ до 3 сек, ранее грузилось дольше.

#37569709 Скорректировать логику получения статусов шаблона (получать также системные статусы эпиков, историй).

---

LeokaEstetica.Platform.Controllers/ModelsValidation/Project/CreateProjectValidationModel.cs
LeokaEstetica.Platform.Database/Repositories/Project/ProjectRepository.cs
LeokaEstetica.Platform.Models/Dto/Input/Project/CreateProjectInput.cs
LeokaEstetica.Platform.Models/Dto/Input/Project/ProjectInput.cs
LeokaEstetica.Platform.Models/Dto/Input/Project/UpdateProjectInput.cs
LeokaEstetica.Platform.Tests/ProjectsTests/CreateProjectTest.cs
LeokaEstetica.Platform.Tests/ProjectsTests/UpdateProjectTest.cs

37661662.Сохранять поле видимости проекта при создании проекта

---

LeokaEstetica.Platform.Controllers/Validators/User/CreateUserValidator.cs

В методе CreateUserValidator не было определено сообщения для некорректного Email, исправлено

38429313 Добавлено сообщение при некорректном вводе Email при регистрации

---

LeokaEstetica.Platform.Database/Abstractions/ProjectManagment/IProjectManagmentRepository.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagment/ProjectManagmentRepository.cs
LeokaEstetica.Platform.Services/Services/ProjectManagment/ProjectManagmentService.cs

Аналогичная проблема была что с названием, что с описанием задач разных типов.

#38230629 Нельзя изменить описание уже созданной истории.

---

LeokaEstetica.Platform.Backend.sln
LeokaEstetica.Platform.Base/Factors/NpgSqlConnectionFactory.cs
LeokaEstetica.Platform.Core/Utils/AutoFac.cs
LeokaEstetica.Platform.Database.Upgrade/Scripts/319.esta.ddl_create_schema_project_management_human_resources.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/320.esta.ddl_create_calendar_events.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/321.esta.ddl_create_calendar_member_status_enum.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/322.esta.ddl_create_calendar_event_members.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/323.esta.ddl_create_calendar_event_role_members.sql
LeokaEstetica.Platform.Database/Abstractions/ProjectManagmentHumanResources/ICalendarRepository.cs
LeokaEstetica.Platform.Database/AutofacModules/RepositoriesModule.cs
LeokaEstetica.Platform.Database/Repositories/ProjectManagmentHumanResources/CalendarRepository.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagementHumanResources/CalendarOutput.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagementHumanResources/EventMemberOutput.cs
LeokaEstetica.Platform.Models/Dto/Output/ProjectManagementHumanResources/EventMemberRoleOutput.cs
LeokaEstetica.Platform.Models/Enums/CalendarEventMemberStatusEnum.cs
LeokaEstetica.Platform.Models/Enums/Enum.cs
LeokaEstetica.Platform.Models/LeokaEstetica.Platform.Models.csproj
LeokaEstetica.Platform.ProjectManagement.HumanResources/Abstractions/ICalendarService.cs
LeokaEstetica.Platform.ProjectManagement.HumanResources/AutofacModules/HumanResourcesModule.cs
LeokaEstetica.Platform.ProjectManagement.HumanResources/Controllers/CalendarController.cs
LeokaEstetica.Platform.ProjectManagement.HumanResources/LeokaEstetica.Platform.ProjectManagement.HumanResources.csproj
LeokaEstetica.Platform.ProjectManagement.HumanResources/Loaders/StartJobs.cs
LeokaEstetica.Platform.ProjectManagement.HumanResources/Program.cs
LeokaEstetica.Platform.ProjectManagement.HumanResources/Properties/launchSettings.json
LeokaEstetica.Platform.ProjectManagement.HumanResources/Services/CalendarService.cs
LeokaEstetica.Platform.ProjectManagement.HumanResources/nlog.config
LeokaEstetica.Platform.ProjectManagement/Controllers/CompanyController.cs

**В рамках PR задачи:**
- #38753193 Добавление календаря. Back.
- #39093328 Добавление нового сервиса HR.
- Подготавливаю архитектуру для отдельного модуля HR, т.к. календарь будет использоваться как в УП, так и в HR и тд.

#38753193 Добавление календаря. Back.

---

LeokaEstetica.Platform.Database.Upgrade/Scripts/319.esta.ddl_alter_project_management_epics.sql
LeokaEstetica.Platform.Database.Upgrade/Scripts/320.esta.ddl_alter_project_management_epics.sql
LeokaEstetica.Platform.Services/Factors/CreateProjectTaskFactory.cs

38999465 Пофиксил ошибку при создании эпиков.

---

LeokaEstetica.Platform.Database/Repositories/ProjectManagment/SprintRepository.cs

Добавил поле created at в в запрос. Это поле в дальнейшем используется для сортировки.

#38908826. Пофиксил сортировку спринтов. 

---

LeokaEstetica.Platform.Database.Upgrade/Scripts/334.esta.create_composite_index_in_component_roles.sql

вручную удалены дубликаты ролей в бд

39496636 добавлена миграция с составным индексом для таблицы

---

LeokaEstetica.Platform.Services/Services/Profile/ProfileService.cs
LeokaEstetica.Platform.Services/Services/Project/ProjectService.cs
LeokaEstetica.Platform.Services/Services/Resume/ResumeService.cs

В профиле - о себе очищены
в каталоге проектов - описание проекта очищены
в вакансиях уже было реализовано

Bugfix/39087748 очищать теги в каталогах вакансий, проектов и анкет у полей описания

---

LeokaEstetica.Platform.Core/Constants/GlobalConfigKeys.cs
LeokaEstetica.Platform.ProjectManagement/Controllers/ConfigController.cs

проверить нейминг ключа и его расположение в классе "Класс ключей модуля УП."
возможно необходимо перенести в другой класс

Feature/39706767 добавить эндпоинт, проверяющий доступность scrum master ai

---

LeokaEstetica.Platform.Database.Upgrade/Scripts/344.esta.ddl_add_index_in_GlobalConfig.sql

удалены дубли и добавлен уникальный индекс ParamKey, ParamType

39706864 Добавить составной индекс на таблицу Configs.GlobalConfig на поля ParamKey, ParamType

---

LeokaEstetica.Platform.Core/Mapper/MappingProfile.cs

добален мапер для OrderEntity, OrderOutput

#39576493 Ошибка при входе в заказы

---

LeokaEstetica.Platform.Models/Dto/Output/Notification/NotificationOutput.cs
LeokaEstetica.Platform.Notifications/Services/ProjectNotificationsService.cs

при необходимости добавлю почту

добавлено название вакансии в выходной модели уведомления проекта

---

LeokaEstetica.Platform.CallCenter/Consts/RemarkConst.cs
LeokaEstetica.Platform.CallCenter/Services/Project/ProjectModerationService.cs
LeokaEstetica.Platform.ProjectManagement.HumanResources/Properties/launchSettings.json

Не давать модератору отклонить проект без внесения замечаний

Добавил предотвращение отклонение проекта без внесения замечаний
